version: '3.8'
services:
  saas-devaten-agent-container:
    image: devaten/saas-devaten-agent:1.0.0
    ports:
      - "8111:8111"
    volumes:
      - ./configurations:/configurations
    environment:
      dashboard-host-url:  app.devaten.com
      dashboard-username:  rahulmore0304@gmail.com
      dashboard-password:  123456
      spring.activemq.broker-url: tcp://18.192.220.39:61616?jms.prefetchPolicy.all=100&jms.redeliveryPolicy.maximumRedeliveries=1