version: '3.8'
services:
  saas-devaten-agent-container:
    image: devaten/saas-devaten-agent:latest
    ports:
      - "8111:8111"
    volumes:
      - ./Configurations/h2/devaten_agentapp_1_0_0.mv:/opt/h2-data/devaten_agentapp_1_0_0.mv:rw
      - ./Configurations/.devaten/.data:/Configurations/.devaten/.data:rw
    environment:
      dashboard-username:  Enter_Your_Dashboard_Login_Email
      dashboard-password:  Enter_Your_Dashboard_Login_Password
